credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: password123
    jdoe:
      email: jdoe@example.com
      name: J Doe
      password: emp123
cookie:
  expiry_days: 30
  key: random_signature_key_123
  name: vincent_cloud_cookie
preauthorized:
  emails:
  - ''
